Traceback (most recent call last):
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class BrowserHistory: 
    
    def __init__(self, homepage: str):
        self.history = Stack()
        self.future  = Stack()
        self.history.push(homepage)

    def visit(self, url: str) -> None:
        self.history.push(url)
        self.future = Stack()

    def back(self, steps: int) -> str:
        while steps > 0 and not self.history.empty():
            self.future.push(self.history.pop())
            steps -= 1
        return self.history.top()
    
    def forward(self, steps: int) -> str:
        while steps > 0 and not self.future.empty():
            self.history.push(self.future.pop())
            steps -= 1
        return self.history.top()

hist = BrowserHistory("leetcode.com")
hist.visit("google.com")
hist.visit("facebook.com")
hist.visit("youtube.com")

assert hist.back(1) == "facebook.com"
assert hist.back(1) == "google.com"
assert hist.forward(1) == "facebook.com"
assert hist.visit("linkedin.com") == None

print("All tests passed.")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 24>[0;34m()[0m
[1;32m     21[0m             steps [38;5;241m-[39m[38;5;241m=[39m [38;5;241m1[39m
[1;32m     22[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mhistory[38;5;241m.[39mtop()
[0;32m---> 24[0m hist [38;5;241m=[39m [43mBrowserHistory[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mleetcode.com[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m     25[0m hist[38;5;241m.[39mvisit([38;5;124m"[39m[38;5;124mgoogle.com[39m[38;5;124m"[39m)
[1;32m     26[0m hist[38;5;241m.[39mvisit([38;5;124m"[39m[38;5;124mfacebook.com[39m[38;5;124m"[39m)

Input [0;32mIn [2][0m, in [0;36mBrowserHistory.__init__[0;34m(self, homepage)[0m
[1;32m      3[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, homepage: [38;5;28mstr[39m):
[0;32m----> 4[0m     [38;5;28mself[39m[38;5;241m.[39mhistory [38;5;241m=[39m [43mStack[49m()
[1;32m      5[0m     [38;5;28mself[39m[38;5;241m.[39mfuture  [38;5;241m=[39m Stack()
[1;32m      6[0m     [38;5;28mself[39m[38;5;241m.[39mhistory[38;5;241m.[39mpush(homepage)

[0;31mNameError[0m: name 'Stack' is not defined
NameError: name 'Stack' is not defined

