Traceback (most recent call last):
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/fsultan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def find_val(sequence, val): 
    
    return val_idx

assert find_val([1, 2, 3, 4, 5])        ==  0, "Test case 1 failed"
assert find_val(["a", "b", "c", "d"]) ==  2, "Test case 2 failed"
assert find_val(["a", "b"], "c")           == -1, "Test case 3 failed"
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mfind_val[39m(sequence, val): 
[1;32m      3[0m     [38;5;28;01mreturn[39;00m val_idx
[0;32m----> 5[0m [38;5;28;01massert[39;00m [43mfind_val[49m[43m([49m[43m[[49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[38;5;241;43m2[39;49m[43m,[49m[43m [49m[38;5;241;43m3[39;49m[43m,[49m[43m [49m[38;5;241;43m4[39;49m[43m,[49m[43m [49m[38;5;241;43m5[39;49m[43m][49m[43m)[49m        [38;5;241m==[39m  [38;5;241m0[39m, [38;5;124m"[39m[38;5;124mTest case 1 failed[39m[38;5;124m"[39m
[1;32m      6[0m [38;5;28;01massert[39;00m find_val([[38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mb[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mc[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124md[39m[38;5;124m"[39m]) [38;5;241m==[39m  [38;5;241m2[39m, [38;5;124m"[39m[38;5;124mTest case 2 failed[39m[38;5;124m"[39m
[1;32m      7[0m [38;5;28;01massert[39;00m find_val([[38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mb[39m[38;5;124m"[39m], [38;5;124m"[39m[38;5;124mc[39m[38;5;124m"[39m)           [38;5;241m==[39m [38;5;241m-[39m[38;5;241m1[39m, [38;5;124m"[39m[38;5;124mTest case 3 failed[39m[38;5;124m"[39m

[0;31mTypeError[0m: find_val() missing 1 required positional argument: 'val'
TypeError: find_val() missing 1 required positional argument: 'val'

